---
abstract: 'Adds automatically an ETag header.'
author:
  - 'franck cuny <franck@lumberjaph.net>'
build_requires:
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110550'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ETag
requires:
  Digest::SHA: 0
  Plack::Middleware: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Plack::Middleware::ETag
  homepage: http://search.cpan.org/perldoc?Plack::Middleware::ETag
  repository: git://github.com/franckcuny/plack-middleware-etag.git
version: 0.03
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: NoTabsTests
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: 0.02
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200004
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200004
