---
abstract: 'Adds automatically an ETag header.'
author:
  - 'franck cuny <franck@lumberjaph.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ETag
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Digest::SHA: 0
  Filter::Util::Call: 0
  HTTP::Request::Common: 0
  Plack: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/franckcuny/plack-middleware-etag.git
version: 0.02
